<?php
return array(
	'DB' => array(
		'database' => 'egamesdummy',
		'host' => 'localhost',
		'password' => 'gosign',
		'username' => 'root',
	),
	'EXT' => array(
		'extListArray' => array(
			'info',
			'perm',
			'func',
			'filelist',
			'extbase',
			'fluid',
			'about',
			'tsconfig_help',
			'context_help',
			'extra_page_cm_options',
			'impexp',
			'sys_note',
			'tstemplate',
			'tstemplate_ceditor',
			'tstemplate_info',
			'tstemplate_objbrowser',
			'tstemplate_analyzer',
			'func_wizards',
			'wizard_crpages',
			'wizard_sortpages',
			'lowlevel',
			'install',
			'belog',
			'beuser',
			'aboutmodules',
			'setup',
			'taskcenter',
			'info_pagetsconfig',
			'viewpage',
			'css_styled_content',
			't3skin',
			't3editor',
			'reports',
			'felogin',
			'form',
			'recycler',
			'saltedpasswords',
			'go_pixelperfect',
			'gridelements',
			'go_backend',
			'tinymce_rte',
			'realurl',
			'static_info_tables',
			'static_info_tables_de',
			'golib_mustache',
			'golib_fal',
			'golib_form',
			'go_language',
			'go_translation',
			'go_404handling',
			'go_tsconfig',
			'go_cachecontrol',
			'go_seo',
			'caretaker_instance',
			'go_caretaker_instance',
			'version',
		),
	),
	'SYS' => array(
		'encryptionKey' => '',
	),
);
?>